USE [C:\DB\MSSQL\TREINAMENTO2018.MDF]

GO

CREATE TABLE ORDERS
(
	ORD_ID INT IDENTITY(1,1) PRIMARY KEY,
	ORD_DESCRIPTION VARCHAR(200),
	ORD_NUMBER VARCHAR(10),
	ORD_DATE DATE
)

GO 

CREATE TABLE ORDER_TYPES
(
	ORT_ID INT IDENTITY(1,1) PRIMARY KEY,
	ORT_DESCRIPTION VARCHAR(200)
)

GO

ALTER TABLE ORDERS
ADD ORD_ORT_ID INT,
	CONSTRAINT ORD_ORT_FK FOREIGN KEY(ORD_ORT_ID) REFERENCES ORDER_TYPES(ORT_ID)