	USE TREINAMENTO2018

	GO

	CREATE TABLE ORDERS
	(
		ORD_ID INT IDENTITY(1,1) PRIMARY KEY,
		ORD_SALESMAN VARCHAR(200),
		ORD_QUANTITY INT,
		ORD_DATE DATE
	)

	GO 

	CREATE TABLE ITEMS
	(
		ITM_ID INT IDENTITY(1,1) PRIMARY KEY,
		ITM_DESCRIPTION VARCHAR(200),
		ITM_COST DECIMAL
	)

	GO

	ALTER TABLE ORDERS
	ADD ORD_ITM_ID INT,
		CONSTRAINT ORD_ITM_FK FOREIGN KEY(ORD_ITM_ID) REFERENCES ITEMS(ITM_ID)